name: personal_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.4.0
  auto_route: ^7.8.3
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  dio_http_formatter: ^3.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.17+2
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  get_it: ^7.6.2
  google_fonts: ^5.1.0
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  responsive_framework: ^1.1.0
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.1.14

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/animations/
    - assets/lottie/

flutter_native_splash:
  android: false
  ios: false
  web: true
  color_web: "#fdfcff"
  color_dark_web: "#1a1c1e"
  image_web: assets/animations/splash_loading.gif
  image_dark_web: assets/animations/splash_loading.gif
